//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDANCKH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_NCKHQBEntities : DbContext
    {
        public QL_NCKHQBEntities()
            : base("name=QL_NCKHQBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietQuyenHT> ChiTietQuyenHTs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<QuyenHeThong> QuyenHeThongs { get; set; }
        public virtual DbSet<DM_DONVI> DM_DONVI { get; set; }
        public virtual DbSet<DM_HOCVI> DM_HOCVI { get; set; }
        public virtual DbSet<DM_LINHVUC_NGHIENCUU> DM_LINHVUC_NGHIENCUU { get; set; }
        public virtual DbSet<DM_LINHVUC_NHIEMVU> DM_LINHVUC_NHIEMVU { get; set; }
        public virtual DbSet<DM_NHIEMVU_NGHIEMTHU> DM_NHIEMVU_NGHIEMTHU { get; set; }
    }
}
