

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLDANCKH.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class QL_NCKHQBEntities : DbContext
{
    public QL_NCKHQBEntities()
        : base("name=QL_NCKHQBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ChiTietQuyenHT> ChiTietQuyenHTs { get; set; }

    public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }

    public virtual DbSet<QuyenHeThong> QuyenHeThongs { get; set; }

    public virtual DbSet<DM_DONVI> DM_DONVI { get; set; }

    public virtual DbSet<DM_HOCVI> DM_HOCVI { get; set; }

    public virtual DbSet<DM_LINHVUC_NGHIENCUU> DM_LINHVUC_NGHIENCUU { get; set; }

    public virtual DbSet<DM_LINHVUC_NHIEMVU> DM_LINHVUC_NHIEMVU { get; set; }


    public virtual int Proc_ChiTietQuyenHT_Delete(string tenDangNhap)
    {

        var tenDangNhapParameter = tenDangNhap != null ?
            new ObjectParameter("TenDangNhap", tenDangNhap) :
            new ObjectParameter("TenDangNhap", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_ChiTietQuyenHT_Delete", tenDangNhapParameter);
    }


    public virtual int Proc_ChiTietQuyenHT_Insert(string tenDangNhap, Nullable<int> idQuyenHeThong)
    {

        var tenDangNhapParameter = tenDangNhap != null ?
            new ObjectParameter("TenDangNhap", tenDangNhap) :
            new ObjectParameter("TenDangNhap", typeof(string));


        var idQuyenHeThongParameter = idQuyenHeThong.HasValue ?
            new ObjectParameter("IdQuyenHeThong", idQuyenHeThong) :
            new ObjectParameter("IdQuyenHeThong", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_ChiTietQuyenHT_Insert", tenDangNhapParameter, idQuyenHeThongParameter);
    }


    public virtual ObjectResult<Proc_ChiTietQuyenHT_Select_Result> Proc_ChiTietQuyenHT_Select(string tenDangNhap)
    {

        var tenDangNhapParameter = tenDangNhap != null ?
            new ObjectParameter("TenDangNhap", tenDangNhap) :
            new ObjectParameter("TenDangNhap", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ChiTietQuyenHT_Select_Result>("Proc_ChiTietQuyenHT_Select", tenDangNhapParameter);
    }


    public virtual ObjectResult<Proc_QuyenHeThong_Select_Result> Proc_QuyenHeThong_Select()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_QuyenHeThong_Select_Result>("Proc_QuyenHeThong_Select");
    }


    public virtual int Proc_ThanhVien_UpdateInfo(Nullable<int> iDNHANVIEN, string tenNhanVien, string trinhdo, string diaChi, Nullable<int> phone, Nullable<bool> trangthai, string quyen)
    {

        var iDNHANVIENParameter = iDNHANVIEN.HasValue ?
            new ObjectParameter("IDNHANVIEN", iDNHANVIEN) :
            new ObjectParameter("IDNHANVIEN", typeof(int));


        var tenNhanVienParameter = tenNhanVien != null ?
            new ObjectParameter("TenNhanVien", tenNhanVien) :
            new ObjectParameter("TenNhanVien", typeof(string));


        var trinhdoParameter = trinhdo != null ?
            new ObjectParameter("Trinhdo", trinhdo) :
            new ObjectParameter("Trinhdo", typeof(string));


        var diaChiParameter = diaChi != null ?
            new ObjectParameter("DiaChi", diaChi) :
            new ObjectParameter("DiaChi", typeof(string));


        var phoneParameter = phone.HasValue ?
            new ObjectParameter("Phone", phone) :
            new ObjectParameter("Phone", typeof(int));


        var trangthaiParameter = trangthai.HasValue ?
            new ObjectParameter("Trangthai", trangthai) :
            new ObjectParameter("Trangthai", typeof(bool));


        var quyenParameter = quyen != null ?
            new ObjectParameter("quyen", quyen) :
            new ObjectParameter("quyen", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_ThanhVien_UpdateInfo", iDNHANVIENParameter, tenNhanVienParameter, trinhdoParameter, diaChiParameter, phoneParameter, trangthaiParameter, quyenParameter);
    }


    public virtual int Proc_ThanhVien_UpdatePass(Nullable<int> iDNHANVIEN, string matkhau)
    {

        var iDNHANVIENParameter = iDNHANVIEN.HasValue ?
            new ObjectParameter("IDNHANVIEN", iDNHANVIEN) :
            new ObjectParameter("IDNHANVIEN", typeof(int));


        var matkhauParameter = matkhau != null ?
            new ObjectParameter("Matkhau", matkhau) :
            new ObjectParameter("Matkhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_ThanhVien_UpdatePass", iDNHANVIENParameter, matkhauParameter);
    }


    public virtual int Proc_ThanhVien_UpdateStatus(Nullable<int> iDNHANVIEN)
    {

        var iDNHANVIENParameter = iDNHANVIEN.HasValue ?
            new ObjectParameter("IDNHANVIEN", iDNHANVIEN) :
            new ObjectParameter("IDNHANVIEN", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_ThanhVien_UpdateStatus", iDNHANVIENParameter);
    }


    public virtual ObjectResult<Proc_ThanhVien_CheckLogIn_Result> Proc_ThanhVien_CheckLogIn(string tenDangNhap, string matKhau)
    {

        var tenDangNhapParameter = tenDangNhap != null ?
            new ObjectParameter("TenDangNhap", tenDangNhap) :
            new ObjectParameter("TenDangNhap", typeof(string));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ThanhVien_CheckLogIn_Result>("Proc_ThanhVien_CheckLogIn", tenDangNhapParameter, matKhauParameter);
    }


    public virtual ObjectResult<Proc_ChiTietQuyenHT_Select_Menu_Result> Proc_ChiTietQuyenHT_Select_Menu(string tenDangNhap)
    {

        var tenDangNhapParameter = tenDangNhap != null ?
            new ObjectParameter("TenDangNhap", tenDangNhap) :
            new ObjectParameter("TenDangNhap", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ChiTietQuyenHT_Select_Menu_Result>("Proc_ChiTietQuyenHT_Select_Menu", tenDangNhapParameter);
    }

}

}

