//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDANCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEXUAT_DATHANG
    {
        public int IDDexuat { get; set; }
        public string Tendexuat { get; set; }
        public string Noidungdexuat { get; set; }
        public Nullable<int> NamDeXuat { get; set; }
        public string CapDeXuat { get; set; }
        public Nullable<bool> TrangthaiPD { get; set; }
        public string LinkTaiLieu { get; set; }
        public string NguoiDeXuat { get; set; }
        public string NguoiPheDuyet { get; set; }
        public Nullable<int> IdLinhVucNC { get; set; }
        public Nullable<int> IdLinhVucNV { get; set; }
        public Nullable<int> DonViThucHien { get; set; }
        public Nullable<bool> ChuyenGiao { get; set; }
        public Nullable<bool> NghiemThu { get; set; }
    }
}
