
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLDANCKH.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DEXUAT_DATHANG
{

    public int IDDexuat { get; set; }

    public string Tendexuat { get; set; }

    public string Noidungdexuat { get; set; }

    public Nullable<int> NamDeXuat { get; set; }

    public string CapDeXuat { get; set; }

    public Nullable<bool> Trangthai { get; set; }

}

}
