//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDANCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHUCDANH
    {
        public int IDChucDanh { get; set; }
        public string TenChucDanh { get; set; }
        public string KyHieuCD { get; set; }
        public Nullable<bool> Trangthai { get; set; }
    }
}
