//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDANCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DONVI
    {
        public int IDDonvi { get; set; }
        public string TenDonvi { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<bool> Trangthai { get; set; }
    }
}
