
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLDANCKH.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DM_LINHVUC_NGHIENCUU
{

    public int IDLinhvuc { get; set; }

    public string TenLinhvuc { get; set; }

    public Nullable<bool> Trangthai { get; set; }

}

}
