//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDANCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHEDUYET_DEXUAT
    {
        public int Id { get; set; }
        public Nullable<int> IDDexuat { get; set; }
        public string Quyetdinhpduyet { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    }
}
