//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDANCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_DANHGIA_CHAMDIEM_HS
    {
        public int ID { get; set; }
        public Nullable<int> IDHS { get; set; }
        public Nullable<int> IDTV { get; set; }
        public Nullable<double> Diem { get; set; }
        public string NguoiCham { get; set; }
    }
}
