//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDANCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEODOITIENDONV
    {
        public int ID { get; set; }
        public Nullable<int> IDDexuat { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string NoiDungBaoCao { get; set; }
        public string FileBaoCao { get; set; }
        public string NoiDungKiemTra { get; set; }
        public string FileKiemTra { get; set; }
    }
}
